name: ZAP CI Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  scans:
    runs-on: ubuntu-latest
    name: ZAP API Scan

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log current directory for debugging
      - name: Log current directory
        run: echo ${PWD}

      # Step 3: Ensure OpenAPI File Exists
      - name: Verify OpenAPI File
        run: |
          if [ ! -f openapi.json ]; then
            echo "openapi.json file not found. Ensure it exists in your repository."
            exit 1
          fi

      # Step 4: Pull ZAP OWASP Docker Image
      - name: Pull ZAP OWASP Image
        run: docker pull zaproxy/zap-weekly

      # Step 5: Run ZAP API Scan
      - name: Run ZAP API Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw \
            -t zaproxy/zap-weekly zap-api-scan.py \
            -t openapi.json -f openapi -c api-scan.conf
